### ISSUE TITLE
Providing data

### ISSUE THREAD

**Issue by chufz** [michaelwitting/RtPredTrainingData#40]
Hi,
I have 4 datasets of two columns I can contribute, can I get the identifiers for it?

**Comment by michaelwitting** [comment]
Hi Caro,

I reserved for you the following IDs:

- 0260
- 0261
- 0262
- 0263

The new template as well as instructions will follow in the next days.

**Comment by michaelwitting** [comment]
Hi Caro,

I merged your pull request. The GitHub actions run into time out due to long calculation time for the classification. I will do the processing offline.

Michael

**Comment by michaelwitting** [comment]
Hi Caro,

your data has been added! Thank you very much for contributing!

Michael
