### ISSUE TITLE
I want to submit a dataset

### ISSUE THREAD

**Issue by Adafede** [michaelwitting/RtPredTrainingData#41]
Hi @michaelwitting, @EvaHarrieder!

As discussed in Dagstuhl, I would have some data to contribute.

Could you define a dataset? (eg. If I have standards analyzed on the same column but in 2 different batches are those 2 datasets?)

Happy to crash-test any template or submission system! 😊

**Comment by michaelwitting** [comment]
Hi,

one dataset for us would be one chromatographic conditions. So if you mean with 2 different batches two different sets of metabolites on the same column and eluents it would be one dataset for us.

**Comment by Adafede** [comment]
Perfect thank you! Then I have a dataset of approx 250 standards on a single column and single condition. However, I have approx 4 adducts per standard, so possibly also 4 retention times. Don't know how convenient it is...gives an idea of how broad the peak can be but may not be the best data to train the model. Also tagging @kruvelab since this might be somehow related

**Comment by michaelwitting** [comment]
Hi,
I reserved for you the study ID 0264. Please find a draft submission guideline and the Excel template attached to this message:

[Template_new.xlsx](https://github.com/michaelwitting/RtPredTrainingData/files/8672437/Template_new.xlsx)
[Data submission to RT data repository.docx](https://github.com/michaelwitting/RtPredTrainingData/files/8672442/Data.submission.to.RT.data.repository.docx)
.

**Comment by michaelwitting** [comment]
Regarding adducts, we typically only accept one RT per substance. Maybe you can share the adduct information directly with @kruvelab?

**Comment by Adafede** [comment]
Ok, I'll then reduce it to a single retention time. 

Having looked at the template, I saw no `pre-column` field. As it is exactly the same phase as the column, shall I include it in the column length?

P.S.: Are all fields mandatory? 
If not, which are the mandatory ones? rt + isomeric smiles, as they should allow computing the rest?

Regarding Classyfire, I have already a bunch of structures classified with https://github.com/aberHRML/classyfireR. It allows caching so could help with the GitHub actions! 😄

**Comment by Adafede** [comment]
Hi @michaelwitting!

Sorry for the time delay.
Here is the first attempt. 
Could you confirm everything needed is in there?

If ok, I'll open a PR to include it.
Any news regarding the precolumn field?

[Template_new.xlsx](https://github.com/michaelwitting/RtPredTrainingData/files/9581527/Template_new.xlsx)
