### ISSUE TITLE
Uploading our data in RtPredTrainingData

### ISSUE THREAD

**Issue by aminasouihi** [michaelwitting/RtPredTrainingData#44]
Hi, 
I would like to upload 44 datasets. 
best regards, 
Amina Souihi

**Comment by michaelwitting** [comment]
Dear Amina,

we reserved you the IDs 0266 to 0309. Please feel free to upload your data.
Can you please supply also name for each dataset, e.g. "Kruve Lab C18 pH 3" or something similar? We will add this to our study overview file.
We observed that we are running into time-out issues for GitHub actions performing the standardization. I suggest to upload the data in smaller batches into the same pull request to avoid time outs.

We can help if you need any further assistance.

Michael
