### ISSUE TITLE
Hi, I would like to add 9 data sets

### ISSUE THREAD

**Issue by joerg-b** [michaelwitting/RtPredTrainingData#82]
these are the ones that I've already discussed with Fleming

**Comment by michaelwitting** [comment]
@f-kretschmer Did you already give some ID to @joerg-b ?

**Comment by michaelwitting** [comment]
Great. Here are the templates we are currently using.
[Template_new.xlsx](https://github.com/michaelwitting/RtPredTrainingData/files/9207666/Template_new.xlsx)

[Data submission to RT data repository.docx](https://github.com/michaelwitting/RtPredTrainingData/files/9207665/Data.submission.to.RT.data.repository.docx)
.
